LOAD DATA LOCAL INFILE 'Bidder.txt' INTO TABLE Bidder COLUMNS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'Seller.txt' INTO TABLE Seller COLUMNS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'Item.txt' INTO TABLE Item COLUMNS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'Category.txt' INTO TABLE Category COLUMNS TERMINATED BY ',';
LOAD DATA LOCAL INFILE 'Bid.txt' INTO TABLE Bid COLUMNS TERMINATED BY ',';
