LOAD DATA LOCAL INFILE 'bidder.txt' INTO TABLE Bidder;
LOAD DATA LOCAL INFILE 'seller.txt' INTO TABLE Seller;
LOAD DATA LOCAL INFILE 'item.txt' INTO TABLE Item;
LOAD DATA LOCAL INFILE 'category.txt' INTO TABLE Category;
LOAD DATA LOCAL INFILE 'bid.txt' INTO TABLE Bid;