LOAD DATA LOCAL INFILE 'Bidder-0.txt' INTO TABLE Bidder COLUMNS TERMINATED BY ',' ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'Seller-0.txt' INTO TABLE Seller COLUMNS TERMINATED BY ',' ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'Item-0.txt' INTO TABLE Item COLUMNS TERMINATED BY ',' ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'Category-0.txt' INTO TABLE Category COLUMNS TERMINATED BY ',' ENCLOSED BY '"';
LOAD DATA LOCAL INFILE 'Bid-0.txt' INTO TABLE Bid COLUMNS TERMINATED BY ',' ENCLOSED BY '"';
